"""link_staff_to_user

Revision ID: 31878daf48ad
Revises: 85b989951dc8
Create Date: 2026-04-28 10:30:47.386156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = '31878daf48ad'
down_revision: Union[str, Sequence[str], None] = '85b989951dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.base.GUID(),
               existing_nullable=False)
        batch_op.alter_column('sale_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('sale_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.base.GUID(),
               existing_nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', app.models.base.GUID(), nullable=True))
        batch_op.alter_column('business_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.base.GUID(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_staff_user', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint('fk_staff_user', type_='foreignkey')
        batch_op.alter_column('business_id',
               existing_type=app.models.base.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=app.models.base.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=app.models.base.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('sale_id',
               existing_type=app.models.base.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.alter_column('sale_id',
               existing_type=app.models.base.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('business_id',
               existing_type=app.models.base.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=app.models.base.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=app.models.base.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
