"""add_email_preferences

Revision ID: 37cd7b2f8c45
Revises: 31878daf48ad
Create Date: 2026-04-28 14:38:20.828925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37cd7b2f8c45'
down_revision: Union[str, Sequence[str], None] = '31878daf48ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('sale_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('sale_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_brief_email_enabled', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('daily_brief_opted_in_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('daily_brief_opted_in_at')
        batch_op.drop_column('daily_brief_email_enabled')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.alter_column('sale_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.alter_column('sale_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.alter_column('business_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###
