"""add_rbac_and_audit_log

Revision ID: 85b989951dc8
Revises: 7ff638b5b1d8
Create Date: 2026-04-28 10:14:30.988394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = '85b989951dc8'
down_revision: Union[str, Sequence[str], None] = '7ff638b5b1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('business_id', app.models.base.GUID(), nullable=False),
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('user_role', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_business_id'), ['business_id'], unique=False)

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.base.GUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('sale_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('sale_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('OWNER', 'CASHIER', name='userrole'), nullable=False, server_default='owner'))
        batch_op.add_column(sa.Column('business_id', app.models.base.GUID(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=app.models.base.GUID(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_users_business_id'), ['business_id'], unique=False)
        batch_op.create_foreign_key('fk_users_business_id', 'businesses', ['business_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_business_id'))
        batch_op.alter_column('id',
               existing_type=app.models.base.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('business_id')
        batch_op.drop_column('role')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=app.models.base.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('business_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=app.models.base.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('business_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=app.models.base.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('sale_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=app.models.base.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('sale_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('business_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=app.models.base.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('business_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=app.models.base.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('business_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=app.models.base.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('owner_id',
               existing_type=app.models.base.GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
